#!/bin/bash

########################COLORS########################

DEFAULT="\033[0m"
HIGHLIGHT="\033[1m"
UNDERLINE="\033[4m"
BLINK="\033[5m"
BLACK="\033[30m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
PURPLE="\033[35m"
CYAN="\033[36m"
WHITE="\033[37m"

######################################################

clear

nop=0
while [ $nop == 0 ]
do
echo "
${GREEN}########## Le scrip du petit codeur ##########

${RED}0. Exit :
${GREEN}1. Delete the cache :
${YELLOW}2. Push :
${CYAN}3. Run 42sh :
${GREEN}4. Who is your best friend ?
${YELLOW}5. Kill bad files :
${CYAN}6. Joue avec moi :${DEFAULT}
"

read var

if [ $var -ne 0 ] && [ $var -ne 1 ] && [ $var -ne 2 ] && [ $var -ne 3 ] &&
[ $var -ne 4 ] && [ $var -ne 5 ] && [ $var -ne 6 ] && [ $var -ne 101 ];
then
echo "${RED}Not a valide choice

${DEFAULT}See you."
read
clear
break
fi

if [ $var == 0 ];
then
echo "${GREEN}See you${DEFAULT}"
clear
exit 0

elif [ $var -eq 1 ];
then
echo "Load...
"
find ~ -name "*.42_cache_bak" -print -delete
echo "
${GREEN}Done :) ${DEFAULT}"
read
clear

elif [ $var -eq 2 ];
then
read -p "entrer le chemin a partir de ce repertoir: " path
cd $path
git add .
git commit -m "${GREEN}done${DEFAULT}"
git push
echo "
${GREEN}Push Done${DEFAULT}

ls-files :
"
git ls-files
echo "
${GREEN}Done${DEFAULT}"

read
clear

elif [ $var -eq 3 ];
then
sh ~/42FileChecker/42FileChecker.sh
read
clear

elif [ $var -eq 4 ];
then
open https://www.google.fr
read
clear

elif [ $var -eq 5 ];
then
find ~ -name "*.dSYM" -print -delete | find ~ -name 'a.out' -print -delete | find ~ -name '.DS_Store' -print -delete | find ~ -name '*.gch' -delete
echo "
${GREEN}Kill done.${DEFAULT}"
read
clear

elif [ $var -eq 6 ];
then

####################GAME############################
win=0
let nb_myst="$RANDOM %100 + 0"
nb_try=10
while [ $nb_try -gt 0 ]
do
echo "Choisi un nombre entre 0 et 100 :  "
read try

if [ $try == "quit" ];
then
nb_try=10
break
fi

if [ $try -lt 0 ] || [ $try -gt 100 ];
then
echo "${RED}entre 0 et 100, lis les consignes..${DEFAULT}"
elif [ $try -ge 0 ] && [ $try -le 100 ];
then
if [ $try -gt $nb_myst ];
then
echo "Le nombre est plus petit."
let nb_try="$nb_try - 1"
echo "il te reste $nb_try essais.
"
elif [ $try -lt $nb_myst ];
then
echo "Le nombre est plus grand."
let nb_try="$nb_try - 1"
echo "il te reste $nb_try essais.
"
else [ $try=$nb_myst ]
echo "${GREEN}You Win Dude! Le nombre etait bien $nb_myst!${DEFAULT}"
win=101
nb_try=10
break
fi

else
echo "il te reste $nb_try essais.
"
fi

done
if [ $win -ne 101 ];
then
echo "${RED}T'as perdu! Il fallait trouver:${DEFAULT} $nb_myst"
fi
nb_try=10
read
clear
####################END GAME############################
elif [ $var -eq 101 ];
then
open https://www.le-101.fr
clear

else
echo "${RED}WHUUUT??${DEFAULT}"
read
clear
fi

done
