#!/bin/sh

########################COLORS########################

DEFAULT="\033[0m"
HIGHLIGHT="\033[1m"
UNDERLINE="\033[4m"
BLINK="\033[5m"
BLACK="\033[30m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
PURPLE="\033[35m"
CYAN="\033[36m"
WHITE="\033[37m"

######################################################

clear

while [ 1 ]
do
	clear
	echo "${CYAN}#############################################
#                  SHIFUMI                  #
#############################################${DEFAULT}

                  ${RED}${UNDERLINE}MODE:${DEFAULT}
	
	
			${RED}
0.	EXIT${YELLOW}

1.	NEW GAME${DEFAULT}


"
	read mode

	if [ $mode -ne 0 ] && [ $mode -ne 1 ];
	then
		echo "${RED}Not a valide choice
	
${GREEN}See you.${DEFAULT}"
#		say "see you"
		clear
		break
	fi	

	if [ $mode -eq 0 ];
	then
		echo "${CYAN}See you.${DEFAULT}"
#		say "see you"
		clear
		exit 0

	elif [ $mode -eq 1 ];
	then
		count=0
		pointmoi=0
		pointbot=0
		while [ 1 ]
		do
			let nb="$RANDOM %3 + 1"
			clear
			echo "${CYAN}      #############################################
      #                 SHIFUMI                   #
      #############################################${DEFAULT}


	                ${UNDERLINE}${YELLOW}ROUND:${DEFAULT} $count ${RED}
0.exit${DEFAULT}						${RED}Points:${DEFAULT} Moi: $pointmoi	
							Bot: $pointbot
${BLUE}${UNDERLINE}CHOOSE:${DEFAULT}

1.pierre
2.feuille
3.ciseau

"
		read var

		if [ $var == 0 ];
		then
			count=1
			break
		fi
	
		if [ $nb -eq 1 ];
		then
			bot="pierre"
		elif [ $nb -eq 2 ];
		then
			bot="feuille"
		elif [ $nb -eq 3 ];
		then
			bot="ciseau"
		fi

		if [ $var -eq 1 ];
		then
			vari="pierre"
		elif [ $var -eq 2 ];
		then
			vari="feuille"
		elif [ $var -eq 3 ];
		then
			vari="ciseau"
		fi

		if [ $var == 1 ] || [ $var == 2 ] || [ $var == 3 ];
		then
			echo "

		${RED} ------>BATTLE<------${DEFAULT}

	  Moi: $vari    VS    Bot: $bot
	"
		let count="$count + 1"

			if [ $bot == "pierre" ] && [ $vari == "feuille" ];
			then
				let pointmoi="$pointmoi + 1"
			elif [ $bot == "feuille" ] && [ $vari == "ciseau" ];
			then
				let pointmoi="$pointmoi + 1"
			elif [ $bot == "ciseau" ] && [ $vari == "pierre" ];
			then
				let pointmoi="$pointmoi + 1"
			elif [ $vari == "pierre" ] && [ $bot == "feuille" ];
			then
				let pointbot="$pointbot + 1"
			elif [ $vari == "feuille" ] && [ $bot == "ciseau" ];
			then
				let pointbot="$pointbot + 1"
			elif [ $vari == "ciseau" ] && [ $bot == "pierre" ];
			then
				let pointbot="$pointbot + 1"
			fi
			echo ""
			read
		fi
		done
	fi
done


























